service: meetup-demo

provider:
  name: aws
  runtime: nodejs6.10
  stage: development
  region: eu-west-1
  environment: ${file(env.${opt:stage, self:provider.stage}.yml)}

functions:
  getMeetups:
    handler: meetups.getMeetups

resources:
  Resources:
    MediaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Meetups-${self:provider.environment.REGION}-${self:provider.environment.STAGE}
        AttributeDefinitions:
          - AttributeName: meetupId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: meetupId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
