service: meetup-demo

provider:
  name: aws
  runtime: nodejs6.10
  stage: development
  region: eu-west-1
  environment: ${file(env.${opt:stage, self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
      Resource: "*"

functions:
  getMeetups:
    handler: meetups.getMeetups
    events:
    - http:
        path: meetups
        method: get
        cors:
          origins:
            - '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
          allowCredentials: false
  createMeetup:
    handler: meetups.createMeetup
    events:
        - http:
            path: createMeetup
            method: post
            cors:
              origins:
                - '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
              allowCredentials: false
resources:
  Resources:
    MediaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Meetups-${self:provider.environment.REGION}-${self:provider.environment.STAGE}
        AttributeDefinitions:
          - AttributeName: meetupId
            AttributeType: S
          - AttributeName: locationId
            AttributeType: S
        KeySchema:
          - AttributeName: meetupId
            KeyType: HASH
          - AttributeName: locationId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
