service: meetup-demo

provider:
  name: aws
  runtime: nodejs6.10
  stage: development
  region: eu-west-1
  environment: ${file(env.${opt:stage, self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:DeleteItem"
      Resource: "*"
plugins:
  - serverless-offline

functions:
  getMeetups:
    handler: meetups.getMeetups
    events:
    - http:
        path: meetup
        method: get
        cors: true
  createMeetup:
    handler: meetups.createMeetup
    events:
    - http:
        path: meetup
        method: post
        cors: true
  deleteMeetup:
    handler: meetups.deleteMeetup
    events:
    - http:
        path: meetup/{id}
        method: delete
        cors: true
        request:
          parameters:
            paths:
              id: true
resources:
  Resources:
    MediaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Meetups-${self:provider.environment.REGION}-${self:provider.environment.STAGE}
        AttributeDefinitions:
          - AttributeName: meetupId
            AttributeType: S
        KeySchema:
          - AttributeName: meetupId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
